[package]
name = "to_from_bytes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rustc-hash = "1.1.0"

atomic_float = "0.1.0"